### ISSUE TITLE
Binary protocol documentation

### ISSUE THREAD

**Issue by Addvilz** [yahoo/pulsar#109]
I saw a websocket docs around, but apart from reading the proto and source, is there any plans to expose and document the binary protocol? Websockets are nice and all, but documented binary protocol could allow for more community client libraries.

**Comment by merlimat** [comment]
Good point. Documenting the binary protocol was on the TODO list although got pushed over a bit. I'll try to get a it shortly.

**Comment by Addvilz** [comment]
Thanks!
