### ISSUE TITLE
Shared mode consumer priority

### ISSUE THREAD

**Issue by DongbinNie** [yahoo/pulsar#134]
Shared mode consumer priority, the messages will only goes to the consumers with higher priority if there's permit, otherwise the message can also be pushed to the consumers with lower priority.

[merlimat]
Good idea. This should be relatively easy to implement. 

[DongbinNie]
:-)

**Comment by rdhabalia** [comment]
- can you describe your usecase where this feature can be helpful?
- and in that usecase: what could be the variables based on which user assign priority level of each consumer? Is it based on machine's capacity or configuration?

**Comment by DongbinNie** [comment]
the consumer may be assigned different priority based on the machine's capacity or location(e.g. rack or idc).

**Comment by merlimat** [comment]
That was what I had in mind as well. My other question would be: do anyone would need more that 2 priorities (`High` and `Low`) in practice?

**Comment by DongbinNie** [comment]
> would anyone need in practice more that 2 priorities (High and Low)?
Currently we only require 2 priorities in the applications, but I think it's better to have the ability to have multiple priorities.
