### ISSUE TITLE
Retention is not enforced when consumers don't advance

### ISSUE THREAD

**Issue by sschepens** [yahoo/pulsar#191]
Retention policies are not enforced a single consumer (or more) don't acknowledge messages.
The issue seems to be [this](https://github.com/yahoo/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L1385), where the oldest acked position for a topic is searched and only older ledgers get discarded.
Is this correct? Should TTL be used instead retention for enforcement?

**Comment by merlimat** [comment]
The thing with retention is that it applies to acknowledged messages. It will keep them around for a minimum amount of time (based on the publish time).

To expire a non-acked message after a certain amount of time, you need to configure TTL.

**Comment by sschepens** [comment]
@merlimat perhaps this should be clarified on the documentaiton, right?

**Comment by merlimat** [comment]
Yes, we should have a page in the features section to describe how to use retention and ttl.
