### ISSUE TITLE
Geo Replication Synced or Asynced

### ISSUE THREAD

**Issue by yiguolei** [yahoo/pulsar#22]
In geo replication scenario, user's request will write to multi region and give user ack? or write to local region and give user ack then forward to other regions asynchronously ?

**Comment by merlimat** [comment]
From https://github.com/yahoo/pulsar/blob/master/docs/GeoReplication.md
> Messages are first persisted in the local cluster, and then forwarded asynchronously to the remote clusters.

The request is written in the local region (with the configured number of replicas), producer will receive ack, and then the messages will be forwarded to remote regions.
