### ISSUE TITLE
UnresolvedAddressException on connection of client

### ISSUE THREAD

**Issue by hakangs** [yahoo/pulsar#228]
#### Expected behavior

I am connecting to server from client code like :

`client = PulsarClient.create("pulsar://192.168.1.28:6650");`

#### Actual behavior

I start the server as standalone. There is no problem when client and server are on the same machine, but when I execute the client code on another pc (in my network), I get the following exception trace:

```
com.yahoo.pulsar.client.api.PulsarClientException
java.util.concurrent.CompletionException
com.yahoo.pulsar.client.api.PulsarClientException
java.nio.channels.UnresolvedAddressException
```

telnet result is successful to port 6650 from client (failing) to server.

What can be the problem ?

#### System configuration
**Pulsar version**: 1.16

**Comment by merlimat** [comment]
Can you paste the logs from the client?

Most probable reason is that the machine running the standalone broker has
a hostname that the client cannot resolve.

Eventually the client needs to connect to a hostname that the broker
self-advertised of itself. By default we use the machine "hostname". You
can override that in the standalone.conf by setting the
advertisedAddress=192.168.1.28 or by passing an option (I think that's -a)
when starting the standalone service.

**Comment by hakangs** [comment]
-a solved my problem, thank you very much.
