### ISSUE TITLE
C++ Build fails but Pulsar build passes

### ISSUE THREAD

**Issue by jai1** [yahoo/pulsar#238]
#### Expected behavior

The Build should fail if C++ clients fails to compile or tests fail

#### Actual behavior

Build continues since compile steps is a part of after_success and as per documentation

> 
The exit code of after_success, after_failure, after_script and subsequent stages do not affect the build result. However, if one of these stages times out, the build is marked as a failure.

Don't know if it was done deliberately since C++ unit tests are a bit flaky

#### Steps to reproduce

Checkin incorrect C++ code 

#### System configuration
**Pulsar version**: x.y

**Comment by merlimat** [comment]
@jai1 was this already fixed?

**Comment by jai1** [comment]
@merlimat -no will work on it next week 
The fix is easy but I have noticed that CPP Tests always fail, I don't want to let CPP Test failures hamper the pulsar build.

**Comment by jai1** [comment]
Only one fix remaining - CPP client crashes on Producer Destruction

**Comment by merlimat** [comment]
Fixed in #492. Running the c++ build and tests in `script` sections after java maven build.
