### ISSUE TITLE
Logs not printed for unit tests

### ISSUE THREAD

**Issue by jai1** [yahoo/pulsar#244]
#### Expected behavior

Log messages (written in test cases) should be printed on the console during build.

#### Actual behavior

Only log messages generated by JUnit like `STARTING TEST, Test succeeded, Before configuration` is be printed, not the ones written in test case.

#### Steps to reproduce

mvn test -B

#### System configuration
**Pulsar version**: x.y

**Comment by merlimat** [comment]
Actually the problem is that you enable logs, you'll reach the max log size for the Travis build and that will make the build fail
