### ISSUE TITLE
Dependency of pulsar/client/api on pulsar/client/impl

### ISSUE THREAD

**Issue by jai1** [yahoo/pulsar#248]
#### Issue

To the best of my knowledge, `pulsar/client/api` should not have dependency on `pulsar/client/impl` 

#### Actual behavior

`pulsar/client/api` has dependency in `pulsar/client/impl`, I think we should create interfaces and remove these dependencies :
```
./AuthenticationFactory.java:import com.yahoo.pulsar.client.impl.auth.AuthenticationDisabled;
./ClientConfiguration.java:import com.yahoo.pulsar.client.impl.auth.AuthenticationDisabled;
./Consumer.java:import com.yahoo.pulsar.client.impl.BrokerConsumerStats;
./Consumer.java:import com.yahoo.pulsar.client.impl.ConsumerStats;
./MessageBuilder.java:import com.yahoo.pulsar.client.impl.MessageBuilderImpl;
./MessageId.java:import com.yahoo.pulsar.client.impl.MessageIdImpl;
./Producer.java:import com.yahoo.pulsar.client.impl.ProducerStats;
./ProducerConfiguration.java:import com.yahoo.pulsar.client.impl.RoundRobinPartitionMessageRouterImpl;
./ProducerConfiguration.java:import com.yahoo.pulsar.client.impl.SinglePartitionMessageRouterImpl;
./PulsarClient.java:import com.yahoo.pulsar.client.impl.PulsarClientImpl;

```
#### Steps to reproduce

Code Inspection

#### System configuration
**Pulsar version**: x.y

**Comment by merlimat** [comment]
I don't see a way to do it with the current API. To be able to do :

```java
PulsarClient client = PulsarClient.create("...");
```

You need to refer to the impl from the api package.

I don't think this is a problem though, since all the code is in the same maven module anyway, and you can still provide an alternative implementation of the api.
