### ISSUE TITLE
Create HTTP Lookup for CPP Client

### ISSUE THREAD

**Issue by jai1** [yahoo/pulsar#307]
In order to do a smooth production roll out we want to bring HTTP Lookup in CPP Client - using libcurl.

**Comment by jai1** [comment]
Can't use boost::asio since we are using bost 1.41 which doesn't have support for native handle

**Comment by jai1** [comment]
@saandrews @msb-at-yahoo 
I was able to get libcurl (Version 7.19.7) with boost (Version 1.41) using curl_multi_socket_action -  
https://github.com/jai1/CPlusPlus-Learn/blob/master/curlExamples/old_curl_asio_without_socket_reuse.cpp

**but** when I ran it with valgrind I saw memory leaks https://gist.github.com/jai1/950d93198eea07ab5522833b40bfd9f6 

I think this is an issue with the old curl library since 
a. I saw checked curl github issues where someone complained about similar memory leak and was instructed to use the new library version.
b. I built and linked the code to the latest version curl library - I see no leaks.

So I am going ahead with Matteos suggestion and creating a thread pool with block curl calls (using easy interface). Let me know if you want me to change the approach.

**Comment by msb-at-yahoo** [comment]
i suggest you default the thread pool size to 1.

**Comment by jai1** [comment]
I ran into this issue with libcurl - https://www.redhat.com/archives/libvir-list/2012-October/msg00210.html

#0  0x00007ffff68ab70b in addbyter (output=110, data=0x7fffcabfbca0) at /home/jai1/curl-master/lib/mprintf.c:998
#1  0x00007ffff68aa543 in dprintf_formatf (data=0x7fffcabfbca0, stream=0x7ffff68ab6d2 <addbyter>, format=0x7ffff68ea1e1 "name lookup timed out", ap_save=0x7fffcabfbce0)
    at /home/jai1/curl-master/lib/mprintf.c:631
#2  0x00007ffff68ab78b in curl_mvsnprintf (buffer=0x0, maxlength=16384, format=0x7ffff68ea1e1 "name lookup timed out", ap_save=0x7fffcabfbce0) at /home/jai1/curl-master/lib/mprintf.c:1016
#3  0x00007ffff688df85 in Curl_failf (data=0x8bc530, fmt=0x7ffff68ea1e1 "name lookup timed out") at /home/jai1/curl-master/lib/sendf.c:248
#4  0x00007ffff687ec72 in Curl_resolv_timeout (conn=0x7ffff737bf3f, hostname=0x7fffcabfbe20 "@\276\277\312\377\177", port=32767, entry=0x7fffb0019368, timeoutms=140737341013673)
    at /home/jai1/curl-master/lib/hostip.c:622
#5  0x00000000008d9b58 in ?? ()
#6  0x00007fffcabfbfd0 in ?? ()

**Comment by merlimat** [comment]
@jai1 Did you see these tips for libcurl in multi-thread apps? 
https://curl.haxx.se/libcurl/c/threadsafe.html

**Comment by jai1** [comment]
@msb-at-yahoo @merlimat 
- Sorry to cause a storm in a teacup, I had not read the document that Matteo sent 

The implementation is done and passes the cms-qa tests - can you please review it and give a +1.
https://github.com/yahoo/pulsar/pull/317
