### ISSUE TITLE
"unackedMessages" stats values keeps increasing

### ISSUE THREAD

**Issue by merlimat** [yahoo/pulsar#369]
#### Expected behavior

In the consumers stats reported for any topic, `unackedMessages` should tell the number of messages pushed to a particular consumer that weren't acked yet.

#### Actual behavior

In exclusive/failover subscription type, the number is not decreased when acks are received (either individual or cumulative) and it's constantly increasing. There is no user-facing problem (delivery is not blocked), but it doesn't make sense to report that number.

#### System configuration
Seems to affect current master and even back to 1.17.2 and 1.16.5 releases. 1.15.7 looks good.

**Comment by merlimat** [comment]
cc @rdhabalia

**Comment by rdhabalia** [comment]
Yes, that make sense and will address it.

**Comment by merlimat** [comment]
I think we could probably just hide the `unackedMessages` and the `blockedForUnackedMessages` on non-shared subscription types.
