### ISSUE TITLE
StackOverflow on asyncReplayEntries

### ISSUE THREAD

**Issue by sschepens** [yahoo/pulsar#383]
I found the following 7 StackOverflows on brokers in the past 24hs on multiple brokers, I'm attaching the traces here, they all seem to come from `asyncReplayEntries`.

[overflow1.txt](https://github.com/yahoo/pulsar/files/956209/overflow1.txt)
[overflow2.txt](https://github.com/yahoo/pulsar/files/956210/overflow2.txt)
[overflow3.txt](https://github.com/yahoo/pulsar/files/956215/overflow3.txt)
[overflow4.txt](https://github.com/yahoo/pulsar/files/956213/overflow4.txt)
[overflow5.txt](https://github.com/yahoo/pulsar/files/956212/overflow5.txt)
[overflow6.txt](https://github.com/yahoo/pulsar/files/956211/overflow6.txt)
[overflow7.txt](https://github.com/yahoo/pulsar/files/956214/overflow7.txt)

**Comment by sschepens** [comment]
Adding details from #380 

>Ok, we have 2 problems then:

>The ManagedCursorImpl.asyncReplayEntries needs to send the response from a different thread always, even though the entries are all in cache. I think this is already the case for normal asynReadEntries() calls

>We should clean up the consumer when this exception happens

**Comment by merlimat** [comment]
@sschepens created PR #384
