### ISSUE TITLE
Avoid Blocking when producer queue full

### ISSUE THREAD

**Issue by jai1** [yahoo/pulsar#395]
Currently, when the producer queue is full we provide two options:-
a. Block the operation
b. Fail the sendAsync operation

I propose that we give another option where we notify the user when there is space available in the queue so instead of blocking the send operation, a user can asynchronously create a task to send the message when space is available on the producer queue.

**One possible use case:-**
Currently, we have given the websocket client producer an option to block if the queue is full. 

https://github.com/yahoo/pulsar/blob/master/pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ProducerHandler.java#L138-L144

If the websocket client producer chooses this option and producer queue is full then the Websocket proxy thread will get blocked.

**Comment by merlimat** [comment]
I think we either rely on the timeout to clear the queue or unblock the thread or we give error immediately. 

Having a separate notification for when the space is available is not really needed and if the application is not careful, it will risk to buffer up a huge amount of messages. 

You can still maintain the count of pending messages and queue it up before hitting the blocking point, or just increase the producer queue size and give error when it's full.

**Comment by merlimat** [comment]
To summarize my point: 
 * If you are doing sync then you want to be blocked
 * If you are doing async, you might have 2 reasons for doing that: 
   1. You care about throughput and want to pipeline messages 
       Use `sendAsync()` with blocking when queue it's full
   2. You have a truly async app --> Use `sendAsync()` with error when queue it's full

**Comment by saandrews** [comment]
I think this will complicate the client logic and implementing it in different client languages might also be a challenge. Looks like we can close it for now and revisit if there is a real use case to address it.

**Comment by jai1** [comment]
Ok - closing the issue
