### ISSUE TITLE
Changing blockIfQueueFull default to false

### ISSUE THREAD

**Issue by jai1** [yahoo/pulsar#422]
Users expect the sendAsync call to be non blocking even when broker is in a bad shape (Restart or GC pause etc) but since blockIfQueueFull is true by default the sendAsync call block which ends up blocking their entire application.

We are planning to change the default blockIfQueueFull to false in our internal wrapper - let me know what you think about this and if you want me to do the same in Pulsar (open source).

**Comment by jai1** [comment]
@merlimat @rdhabalia @saandrews @msb-at-yahoo @sschepens

**Comment by sschepens** [comment]
Totally agree, `blockIfQUeueFull` should default to `false`

**Comment by saandrews** [comment]
I also vote to change the default to false.

**Comment by merlimat** [comment]
I agree too. Would it make sense to increase the default queue size as well? 

If you're publishing 1K msg/s, a queue size of 1K will buffer up for 1 seconds. After that you will start seeing publish failures.

**Comment by jai1** [comment]
@merlimat - I agree that the number of publish failures may go up in case broker is unresponsive even for a second. 
@saandrews @rdhabalia - Does 5K seem a good number - I don't think any property publishes more than 1K mps so 5K limit will give the broker 5 seconds breathing space in case of GC pauses.

**Comment by saandrews** [comment]
I was thinking 30k which covers our timeout duration. But client mem usage will shoot up. Any thoughts @merlimat ?
