### ISSUE TITLE
Limit the number of messages kept in pendingAddEntries

### ISSUE THREAD

**Issue by saandrews** [yahoo/pulsar#424]
Client has the ability to set the producer queue size. If the size is misconfigured and producer started to produce faster than broker can write to bookie, these messages are kept in pendingAddEntries by ManagedLedger. Without any limit in this queue, we could fill up this queue and exhaust broker memory.

Proposed options:
1. Enforce a limit on the client queue size
2. Enforce a limit on the number of entries in pendingAddEntries
3. Reject any send request once the number of entries in pendingAddEntries reached the configured value

**Comment by merlimat** [comment]
There is already a limit of 1K pending entries for a given TCP connection. After that the broker stops reading from that connection.

**Comment by saandrews** [comment]
Oh, yeah. Forgot about it. Closing this issue.
