### ISSUE TITLE
Message rate out with batches is counting batches/s

### ISSUE THREAD

**Issue by merlimat** [yahoo/pulsar#466]
#### Expected behavior

When publishing with transparent batching the message rate in is correctly 
displayed as msg/s, but the rate out is just counting the batches. 

Same thing happens with the backlog count. I think we should have been 
displaying an estimated of the *messages* in the backlog.

**Comment by jai1** [comment]
Fixed in #462

**Comment by merlimat** [comment]
@jai1 This is unrelated with #462. It happens with Java as well. It's just on the rate out side.

**Comment by jai1** [comment]
Sorry for the confusion 

I think I found the issue 
https://github.com/yahoo/pulsar/blob/master/pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/Consumer.java

Need to change 
                msgOut.recordEvent(metadataAndPayload.readableBytes());
To
                msgOut.recordMultipleEvents(metadataAndPayload.getNumMessagesInBatch(), metadataAndPayload.readableBytes());

Will test the change tomorrow and raise a PR.
