### ISSUE TITLE
SimpleDateFormat is not thread safe

### ISSUE THREAD

**Issue by xuwei-k** [yahoo/pulsar#62]
- https://github.com/yahoo/pulsar/blob/1304d4b44d/pulsar-broker/src/main/java/com/yahoo/pulsar/broker/admin/PersistentTopics.java#L105
- https://github.com/yahoo/pulsar/blob/1304d4b44d/pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/persistent/PersistentTopic.java#L121
- https://github.com/yahoo/pulsar/blob/1304d4b44d/pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ProducerImpl.java#L1094
- https://github.com/yahoo/pulsar/blob/1304d4b44d/pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ConsumerHandler.java#L195

**Comment by merlimat** [comment]
Thank you for pointing this out. For some reason it seemed obvious that `SimpleDateFormat` should be thread-safe, but the javadoc it's pretty clear in that is not true.

I think we should just wrap all these instances with a `FastThreadLocal` class.

**Comment by maskit** [comment]
Oops, I haven't read @merlimat 's comment. I just sent a PR to replace the formatters with DateTimeFormatter.

**Comment by merlimat** [comment]
@maskit actually `DateTimeFormatter` looks like a much better option (I didn't know about that class), since thread locals have some overhead
