### ISSUE TITLE
The JSON License is a risk

### ISSUE THREAD

**Issue by yush1ga** [yahoo/pulsar#86]
Pulsar depends on [Json](https://mvnrepository.com/artifact/org.json/json/20090211), which is one of Java Library, and its license is "The JSON License".
"The JSON License" includes the following sentence 

"The Software shall be used for Good, not Evil."

and some people consider that it is a risk because it cannot be judged what is Evil.

I consider that Json should be replaced with alternative library to have many people and companies  use Pulsar.

**Comment by maskit** [comment]
FYI, Apache products have been unable to include works under JSON license.
https://www.apache.org/legal/resolved#json

A discussion about alternatives is on-going.
https://mail-archives.apache.org/mod_mbox/www-legal-discuss/201611.mbox/browser

**Comment by merlimat** [comment]
From the email thread, there's a link to a Debian page with few suggested alternatives. 

https://wiki.debian.org/qa.debian.org/jsonevil

Maybe using any of these, would avoid making any code change.

**Comment by merlimat** [comment]
Merged fix from #130 in 6ea847c
